/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnes;

import javax.swing.JOptionPane;

/**
 *
 * @author wedad
 */
public class Login extends javax.swing.JFrame {

  
   
    /**
     * Creates new form Login
     */
    public Login() {
        
        
        initComponents();
          
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        n = new javax.swing.JFormattedTextField();
        p = new javax.swing.JPasswordField();
        ent = new javax.swing.JButton();
        jb = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnes/dd.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnes/dd.jpg"))); // NOI18N

        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(650, 300, 300, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 192, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User name :");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        n.setBackground(new java.awt.Color(204, 204, 204));
        n.setForeground(new java.awt.Color(255, 0, 51));
        n.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 230, 30));

        p.setBackground(new java.awt.Color(204, 204, 204));
        p.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 230, 30));

        ent.setBackground(new java.awt.Color(0, 51, 153));
        ent.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ent.setForeground(new java.awt.Color(255, 255, 255));
        ent.setText("Log In");
        ent.setAlignmentX(200.0F);
        ent.setAlignmentY(400.0F);
        ent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entActionPerformed(evt);
            }
        });
        ent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entKeyPressed(evt);
            }
        });
        getContentPane().add(ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 278, 90, 40));

        jb.setBackground(new java.awt.Color(255, 0, 51));
        jb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jb.setForeground(new java.awt.Color(255, 255, 255));
        jb.setText("Cancel");
        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });
        getContentPane().add(jb, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 280, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnes/cam.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnes/th.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entActionPerformed
        
       
        
        
        String x = n.getText();
        
        
        
        
        
        String y = p.getText();
        
        if(x.equals("Fitness") && y.equals("Mojmilo")){
        
        new Test().setVisible(true);
      
       
         
        
        
        }
        else{
        
            JOptionPane.showMessageDialog(null, "Wrong user name or password");
        
        
        }
        
    }//GEN-LAST:event_entActionPerformed

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed
       
        new Login().hide();
    }//GEN-LAST:event_jbActionPerformed

    private void entKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entKeyPressed
        ent.getRootPane().setDefaultButton(ent);
    }//GEN-LAST:event_entKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jb;
    private javax.swing.JFormattedTextField n;
    private javax.swing.JPasswordField p;
    // End of variables declaration//GEN-END:variables
}
